{
 "title": "[FUNTER] - CONSULTA BASE DE CARTEIRA - V2.0",
 "tags": [ "Elleven" ],
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   { "name": "razao_social", "label": "Razão Social" },
   { "name": "nome_fantasia", "label": "Nome Fantasia" },
   { "name": "CNPJ" },
   { "name": "id_contrato", "label": "ID Contrato" },
   {
    "name": "Clientes",
    "label": "Clientes",
    "query": "SELECT \n Cliente.id\n\nFROM\n  people AS Cliente\n  LEFT JOIN contracts Contratos ON Cliente.id = Contratos.client_id\n  LEFT JOIN people_crm_informations pci ON pci.person_id = Cliente.id\n  LEFT JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\nWHERE Vendedor.id = $GN\n\n\n"
   },
   {
    "name": "Contrato",
    "query": "SELECT \nCONCAT( Contratos.id, '__',  Contratos.description)\n\nFROM\n  people AS Clientes\n  LEFT JOIN contracts Contratos ON Clientes.id = Contratos.client_id\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\nWHERE\n  Clientes.id IN ($Clientes)\n  AND Vendedor.id = $GN\n  AND Contratos.v_stage != 'Cancelado' -- Aspas simples para string literal\n"
   },
   {
    "name": "Produtos",
    "query": "SELECT\n\nCONCAT( Produtos.code, '__', Produtos.title)\n\nFROM people Clientes\nJOIN contracts Contratos ON Clientes.id=Contratos.client_id AND Contratos.deleted = false\nLEFT JOIN people Vendedor ON Contratos.seller_1_id = Vendedor.user_id\nLEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id AND RCI.deleted = false\nLEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\n\nWHERE Contratos.id IN ($Contrato)\n\n-- and RCI.is_composition = false\nGROUP by Produtos.id"
   },
   {
    "name": "GN",
    "query": "SELECT \nCONCAT(Vendedor.id, '__', Vendedor.name)\n\n FROM people AS Cliente \n INNER JOIN people_crm_informations pci ON pci.person_id = Cliente.id\n INNER JOIN people AS Vendedor ON Vendedor.id=pci.proprietary_id\n"
   },
   {
    "name": "contatos",
    "query": "SELECT\n  Contato.id\nFROM\n  people Clientes\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\n  INNER JOIN people_contacts PC ON PC.person_id = Clientes.id\n  INNER JOIN people Contato ON Contato.id = PC.contact_id\nwhere\n  Clientes.id IN ($Clientes)\n  AND Vendedor.id = $GN"
   }
  ]
 },
 "panels": [
  { "title": "Painel Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "options": {
    "content": "<div id=\"scalable-container\" style=\"width:100%; height:100%; display:flex; flex-direction:column; justify-content:center; align-items:center; padding:5px;\">\r\n  <h1 id=\"title-text\" style=\"margin:0; color:#66FF66; font-family:Arial, sans-serif; text-shadow:1px 1px 2px rgba(0,0,0,0.5); white-space:nowrap;\">\r\n    Carteira <span style=\"color:#FF4500;\">GN$GN</span>\r\n  </h1>\r\n  <h2 id=\"value-text\" style=\"margin:0; color:#66FF66; font-family:Arial, sans-serif; text-shadow:1px 1px 2px rgba(0,0,0,0.5); white-space:nowrap;\">\r\n    <span style=\"color:#f3b29b;\">${GN:text}</span>\r\n  </h2>\r\n</div>\r\n"
   }
  },
  {
   "title": "Grupo Clientes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  coalesce(Insignia.title, '(Campo não preenchido)') AS \"Grupo Clientes\",\r\n  COUNT(DISTINCT Clientes.id) AS \"Quantidade\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations as pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people as Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN insignias as Insignia on Insignia.id = Clientes.insignia_id\r\nWHERE\r\n  Vendedor.id = $GN -- (Acassio Maciel) Filtro do vendedor\r\n    AND Contratos.v_stage != 'Cancelado' -- Aspas simples para string literal\r\n\r\nGROUP BY\r\n  Insignia.title\r\nORDER BY\r\n  \"Quantidade\" DESC"
    }
   ]
  },
  {
   "title": "Quant. Clientes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    Cliente.id AS \"Código\"\r\n\r\n FROM people AS Cliente \r\n LEFT JOIN contracts Contratos ON Cliente.id = Contratos.client_id\r\n LEFT JOIN people_crm_informations pci ON pci.person_id = Cliente.id\r\n LEFT JOIN people AS Vendedor ON Vendedor.id=pci.proprietary_id\r\n\r\nWHERE Vendedor.id = $GN\r\nAND Contratos.v_stage != 'Cancelado' -- Aspas simples para string literal\r\n\r\ngroup by Cliente.id\r\n"
    }
   ]
  },
  {
   "title": "Quant. Contratos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Contratos.id AS \"Contrato\"\r\n  -- Contratos.v_stage AS \"Status Contrato\"\r\nFROM\r\n  people AS Cliente\r\n  LEFT JOIN contracts Contratos ON Cliente.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Cliente.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nWHERE\r\n  Vendedor.id = $GN\r\n  AND Contratos.v_stage != 'Cancelado' -- Aspas simples para string literal\r\nORDER BY\r\n  \"Contrato\""
    }
   ]
  },
  {
   "title": "Valor Da carteira",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CONCAT('R$ ', FORMAT(SUM(Contratos.amount), 2, 'de_DE')) AS \"Valor Contrato\"\r\n\r\nFROM people as Clientes\r\nINNER JOIN contracts as Contratos ON Contratos.client_id = Clientes.id\r\nINNER JOIN people_crm_informations as pci ON pci.person_id = Clientes.id\r\nINNER JOIN people as Vendedor ON Vendedor.id = pci.proprietary_id\r\n\r\nWHERE \r\nContratos.v_stage != 'Cancelado'  -- Adicionei filtro para excluir cancelados\r\nAND Vendedor.id = $GN -- (Acassio Maciel) Filtro do vendedor\r\n\r\n"
    }
   ]
  },
  {
   "title": "Ticket Médio de contratos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT ('R$ ', FORMAT (AVG(Contratos.amount), 2, 'de_DE')) AS \"Valor Contrato\"\nFROM\n  people as Clientes\n  INNER JOIN contracts as Contratos ON Contratos.client_id = Clientes.id\n  INNER JOIN people_crm_informations as pci ON pci.person_id = Clientes.id\n  INNER JOIN people as Vendedor ON Vendedor.id = pci.proprietary_id\nWHERE\n  Contratos.v_stage != 'Cancelado' -- Adicionei filtro para excluir cancelados\n  AND Vendedor.id = $GN -- (Acassio Maciel) Filtro do vendedor"
    }
   ]
  },
  {
   "title": "Contratos filtrados por data de finalização",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Contratos filtrados por data de finalização",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    Cliente.id AS \"codigo_cliente\",\r\n    Cliente.name AS \"Razão social\",\r\n    -- TO_CHAR(Contratos.date, 'DD/MM/YYYY') as \"Data contrato\"\r\n        CONCAT(\r\n    SUBSTRING(Cliente.tx_id, 1, 2), '.',       -- primeiros dois dígitos\r\n    SUBSTRING(Cliente.tx_id, 3, 3), '.',       -- três dígitos do meio\r\n    SUBSTRING(Cliente.tx_id, 6, 3), '/',       -- mais três dígitos\r\n    SUBSTRING(Cliente.tx_id, 9, 4), '-',       -- quatro dígitos antes do traço\r\n    SUBSTRING(Cliente.tx_id, 13, 2)            -- últimos dois dígitos\r\n  ) AS \"CNPJ\",\r\n  Contratos.id AS \"Contrato\",\r\n  DATE_FORMAT(beginning_date, '%d/%m/%Y') AS \"Data de inicio\",\r\n  DATE_FORMAT(final_date, '%d/%m/%Y') AS \"Data de finalização\"\r\n\r\n    -- Contratos.seller_1_id AS \"ID vendedor\",\r\n    -- Vendedor.name AS \"Vendedor\"\r\nFROM\r\n  people AS Cliente\r\n  LEFT JOIN contracts Contratos ON Cliente.id = Contratos.client_id\r\n  LEFT JOIN people_crm_informations pci ON pci.person_id = Cliente.id\r\n  LEFT JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nWHERE Vendedor.id = $GN\r\nAND (\r\n    -- Se a variável não foi preenchida no Grafana\r\n    '${razao_social}' = '' \r\n    OR \r\n    -- Se foi preenchida, faz a busca com LIKE\r\n    Cliente.name ILIKE '%${razao_social}%'\r\n)\r\nAND (\r\n    -- Se a variável não foi preenchida no Grafana\r\n    '${nome_fantasia}' = '' \r\n    OR \r\n    -- Se foi preenchida, faz a busca com LIKE\r\n    Cliente.name_2 ILIKE '%${nome_fantasia}%'\r\n)\r\nAND (\r\n    -- Se a variável não foi preenchida no Grafana\r\n    '${CNPJ}' = '' \r\n    OR \r\n    -- Se foi preenchida, faz a busca com LIKE\r\n    Cliente.tx_id ILIKE '%${CNPJ}%'\r\n)\r\nAND (\r\n    '${id_contrato}' = '' \r\n    OR \r\n    Contratos.id::text ILIKE '%${id_contrato}%'\r\n)\r\nAND Contratos.v_stage != 'Cancelado'  -- Adicionei filtro para excluir cancelados\r\nAND final_date BETWEEN $__timeFrom() AND $__timeTo()\r\n-- group by Cliente.id\r\n-- LIMIT 10\r\n"
    }
   ]
  },
  { "title": "Clientes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Lista Clientes",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    Cliente.id AS \"Código\",\r\n    Cliente.name AS \"Razão social\",\r\n    -- TO_CHAR(Contratos.date, 'DD/MM/YYYY') as \"Data contrato\"\r\n        CONCAT(\r\n    SUBSTRING(Cliente.tx_id, 1, 2), '.',       -- primeiros dois dígitos\r\n    SUBSTRING(Cliente.tx_id, 3, 3), '.',       -- três dígitos do meio\r\n    SUBSTRING(Cliente.tx_id, 6, 3), '/',       -- mais três dígitos\r\n    SUBSTRING(Cliente.tx_id, 9, 4), '-',       -- quatro dígitos antes do traço\r\n    SUBSTRING(Cliente.tx_id, 13, 2)            -- últimos dois dígitos\r\n  ) AS \"CNPJ\"\r\n\r\n    -- Contratos.seller_1_id AS \"ID vendedor\",\r\n    -- Vendedor.name AS \"Vendedor\"\r\nFROM\r\n  people AS Cliente\r\n  LEFT JOIN contracts Contratos ON Cliente.id = Contratos.client_id\r\n  LEFT JOIN people_crm_informations pci ON pci.person_id = Cliente.id\r\n  LEFT JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nWHERE Vendedor.id = $GN\r\nAND (\r\n    -- Se a variável não foi preenchida no Grafana\r\n    '${razao_social}' = '' \r\n    OR \r\n    -- Se foi preenchida, faz a busca com LIKE\r\n    Cliente.name ILIKE '%${razao_social}%'\r\n)\r\nAND (\r\n    -- Se a variável não foi preenchida no Grafana\r\n    '${nome_fantasia}' = '' \r\n    OR \r\n    -- Se foi preenchida, faz a busca com LIKE\r\n    Cliente.name_2 ILIKE '%${nome_fantasia}%'\r\n)\r\nAND (\r\n    -- Se a variável não foi preenchida no Grafana\r\n    '${CNPJ}' = '' \r\n    OR \r\n    -- Se foi preenchida, faz a busca com LIKE\r\n    Cliente.tx_id ILIKE '%${CNPJ}%'\r\n)\r\nAND (\r\n    '${id_contrato}' = '' \r\n    OR \r\n    Contratos.id::text ILIKE '%${id_contrato}%'\r\n)\r\nAND Contratos.v_stage != 'Cancelado'  -- Adicionei filtro para excluir cancelados\r\ngroup by Cliente.id\r\n-- LIMIT 10\r\n"
    }
   ]
  },
  {
   "title": "Razão Social",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Clientes.name AS \"Razão Social\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Vendedor.id = $GN"
    }
   ]
  },
  {
   "title": "Contratos",
   "type": "table",
   "description": "Informação dos contratos do Cliente",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Contratos.id AS \"Contrato\",\r\n  Contratos.v_stage AS \"Status\",\r\n  Contratos.v_status as \"Estagio \"\r\nFROM\r\n  people AS Clientes\r\n  LEFT JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nWHERE\r\n  Clientes.id IN ($Clientes)\r\n  AND Vendedor.id = $GN\r\n  -- AND Contratos.v_stage != 'Cancelado' -- Aspas simples para string literal\r\nORDER BY\r\n  \"Contrato\""
    }
   ]
  },
  {
   "title": "Nome Fantasia",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n coalesce(Clientes.name_2, '(Campo não preenchido)') AS \"Nome Fantasia\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Vendedor.id = $GN"
    }
   ]
  },
  {
   "title": "CNPJ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CONCAT(\r\n    SUBSTRING(Clientes.tx_id, 1, 2), '.',       -- primeiros dois dígitos\r\n    SUBSTRING(Clientes.tx_id, 3, 3), '.',       -- três dígitos do meio\r\n    SUBSTRING(Clientes.tx_id, 6, 3), '/',       -- mais três dígitos\r\n    SUBSTRING(Clientes.tx_id, 9, 4), '-',       -- quatro dígitos antes do traço\r\n    SUBSTRING(Clientes.tx_id, 13, 2)            -- últimos dois dígitos\r\n  ) AS \"CNPJ\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Vendedor.id = $GN"
    }
   ]
  },
  {
   "title": "Valor Do Contrato",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CONCAT ('R$ ', FORMAT (SUM(Contratos.amount), 2, 'de_DE')) AS \"Valor Contrato\"\r\nFROM\r\n  people AS Clientes\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\nWHERE\r\n  Vendedor.id = $GN\r\n  AND Clientes.id IN ($Clientes)\r\n  AND Contratos.v_stage != 'Cancelado' -- Adicionei filtro para excluir cancelados"
    }
   ]
  },
  {
   "title": "Telefone contato",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Clientes.phone AS \"Telefone\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Vendedor.id = $GN"
    }
   ]
  },
  {
   "title": "Celular contato",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Clientes.cell_phone_1 AS \"Telefone\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Vendedor.id = $GN"
    }
   ]
  },
  {
   "title": "Email contato",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Clientes.email AS \"Email\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Vendedor.id = $GN"
    }
   ]
  },
  {
   "title": "Grupo Clientes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  coalesce(Insignia.title, '(Campo não preenchido)') AS \"Grupo Clientes\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations as pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people as Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN insignias as Insignia on Insignia.id = Clientes.insignia_id\r\nWHERE\r\n  Clientes.id IN ($Clientes)\r\n  AND Vendedor.id = $GN"
    }
   ]
  },
  {
   "title": "Quant. Contratos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Contratos.id AS \"Contrato\"\r\nFROM\r\n  people AS Clientes\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  INNER JOIN contracts as Contratos ON Contratos.client_id = Clientes.id\r\nWHERE\r\n  Clientes.id IN ('$Clientes')\r\n  AND Vendedor.id = $GN\r\n  AND Contratos.v_stage != 'Cancelado' -- Aspas simples para string literal\r\nORDER BY\r\n  \"Contrato\""
    }
   ]
  },
  {
   "title": "Mais Contatos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nome contato",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 36 },
     "repeat": "contatos",
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Contato.name AS \"Nome\"\r\nFROM\r\n  people Clientes\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  JOIN people_contacts PC ON PC.person_id = Clientes.id\r\n  JOIN people Contato ON Contato.id = PC.contact_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Contato.id IN ($contatos)\r\n  AND Vendedor.id = $GN"
      }
     ]
    },
    {
     "title": "Email contato",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 7, "y": 36 },
     "repeat": "contatos",
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Contato.email AS \"Email\"\r\nFROM\r\n  people Clientes\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  JOIN people_contacts PC ON PC.person_id = Clientes.id\r\n  JOIN people Contato ON Contato.id = PC.contact_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Contato.id IN ($contatos)\r\n  AND Vendedor.id = $GN"
      }
     ]
    },
    {
     "title": "Telefone contato",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 36 },
     "repeat": "contatos",
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Contato.phone AS \"Telefone\"\r\nFROM\r\n  people Clientes\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  JOIN people_contacts PC ON PC.person_id = Clientes.id\r\n  JOIN people Contato ON Contato.id = PC.contact_id\r\nwhere\r\n  Clientes.id IN ($Clientes)\r\n  AND Contato.id IN ($contatos)\r\n  AND Vendedor.id = $GN"
      }
     ]
    }
   ]
  },
  {
   "title": "$Contrato",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "ID Contrato",
     "type": "stat",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  Contratos.id AS \"Contrato\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\n  -- Order by \"Contrato\""
      }
     ]
    },
    {
     "title": "Valor Contrato",
     "type": "stat",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  CONCAT('R$ ', FORMAT(Contratos.amount, 2, 'de_DE')) AS \"Valor Contrato\" \r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN"
      }
     ]
    },
    {
     "title": "Vendedor Contrato",
     "type": "stat",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 4, "w": 10, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Vendedor.name AS \"Vendedor\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN"
      }
     ]
    },
    {
     "title": "Produtos",
     "type": "table",
     "description": "Produtos adquiridos mediante ao contrato",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 40 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  -- Contratos.id AS \"Contrato\",\r\n  Produtos.title AS \"Produto\",\r\n  Produtos.code AS \"Código\",\r\n  Etiquetas.service_tag AS \"Etiqueta\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN contract_service_tags Etiquetas ON Etiquetas.id = RCI.contract_service_tag_id\r\nWHERE\r\n  Contratos.id IN ($Contrato)\r\n  -- and RCI.is_composition = false\r\n  AND Vendedor.id = $GN"
      }
     ]
    },
    {
     "title": "Descrição",
     "type": "stat",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Contratos.description AS \"Descrição Contrato\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\n"
      }
     ]
    },
    {
     "title": "Ciclo faturamento",
     "type": "stat",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 3, "w": 5, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  CDC.title  AS \"Contrato\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  INNER JOIN contract_date_configurations CDC ON CDC.id = Contratos.contract_date_configuration_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\n  -- Order by \"Contrato\""
      }
     ]
    },
    {
     "title": "Dia de Vencimento",
     "type": "stat",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 3, "w": 5, "x": 13, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  CDC.collection_day  AS \"Contrato\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  INNER JOIN contract_date_configurations CDC ON CDC.id = Contratos.contract_date_configuration_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\n  -- Order by \"Contrato\""
      }
     ]
    },
    {
     "title": "Datas Contrato",
     "type": "table",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 4, "w": 10, "x": 8, "y": 47 },
     "targets": [
      {
       "rawSql": "SELECT \r\n  DATE_FORMAT(beginning_date, '%d/%m/%Y') AS \"Data de inicio\", \r\n  DATE_FORMAT(final_date, '%d/%m/%Y') AS \"Data de finalização\",\r\n  DATE_FORMAT(billing_beginning_date, '%d/%m/%Y') AS \"Inicio de Faturamento\", \r\n  DATE_FORMAT(billing_final_date, '%d/%m/%Y') AS \"Final de faturamento\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN"
      }
     ]
    },
    {
     "title": "Estágio do Contrato",
     "type": "stat",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  Contratos.v_status AS \"Contrato\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\n  -- Order by \"Contrato\""
      }
     ]
    },
    {
     "title": "Status do Contrato",
     "type": "stat",
     "description": "Informação do contrato ${Contrato} do Cliente",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  Contratos.v_stage AS \"Contrato\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nwhere\r\n  Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\n  -- Order by \"Contrato\""
      }
     ]
    },
    {
     "title": "Endereço",
     "type": "stat",
     "description": "Endereço da contratação",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  CONCAT (\r\n    Endereco.street,\r\n    ', ',\r\n    Endereco.number,\r\n    CASE\r\n      WHEN Endereco.address_complement IS NOT NULL\r\n      AND Endereco.address_complement != '' THEN CONCAT (' - ', Endereco.address_complement)\r\n      ELSE ''\r\n    END,\r\n    ' - ',\r\n    Endereco.neighborhood\r\n  ) as \"Endereço Completo\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  LEFT JOIN people_addresses Endereco ON Endereco.id = Contratos.people_address_id\r\nWHERE\r\n  RCI.is_composition = false\r\n  AND Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\nGROUP BY\r\n  Endereco.id"
      }
     ]
    },
    {
     "title": "CEP",
     "type": "stat",
     "description": "CEP da contratação",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  Endereco.postal_code as \"CEP\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  LEFT JOIN people_addresses Endereco ON Endereco.id = Contratos.people_address_id\r\nWHERE\r\n  RCI.is_composition = false\r\n  AND Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\nGROUP BY\r\n  Endereco.id"
      }
     ]
    },
    {
     "title": "Cidade",
     "type": "stat",
     "description": "Cidade da contratação",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  CONCAT(Endereco.city, ' - ', Endereco.state, ', ', Endereco.country) as \"Endereço\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  LEFT JOIN people_addresses Endereco ON Endereco.id = Contratos.people_address_id\r\nWHERE\r\n  RCI.is_composition = false\r\n  AND Clientes.id = ($Clientes)\r\n  AND Contratos.id = ($Contrato)\r\n  AND Vendedor.id = $GN\r\nGROUP BY\r\n  Endereco.id"
      }
     ]
    }
   ]
  },
  {
   "title": "$Produtos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "Produtos",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Produtos.title AS \"Produto\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n"
      }
     ]
    },
    {
     "title": "Código",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Produtos.code AS \"Código\"\r\nFROM\r\n  contract_items RCI\r\n  JOIN contracts Contratos ON Contratos.id = RCI.contract_id\r\n  JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN people Clientes ON Clientes.id = Contratos.client_id\r\n  JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nWHERE\r\n  Contratos.id IN ($Contrato)\r\n  AND Produtos.code IN ($Produtos)\r\n  -- and RCI.is_composition = false\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n  \r\n  Group by Produtos.code"
      }
     ]
    },
    {
     "title": "Etiqueta Descrição",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Etiquetas.description AS \"Etiqueta Descrição\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN contract_service_tags Etiquetas ON Etiquetas.id = RCI.contract_service_tag_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n"
      }
     ]
    },
    {
     "title": "Valor",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  RCI.total_amount AS \"Valor Produto\"\r\nFROM\r\n  contract_items RCI\r\n  JOIN contracts Contratos ON Contratos.id = RCI.contract_id\r\n  JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN people Clientes ON Clientes.id = Contratos.client_id\r\n  JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\nWHERE\r\n  Contratos.id IN ($Contrato)\r\n  AND Produtos.code IN ($Produtos)\r\n  -- and RCI.is_composition = false\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n  \r\n  group by RCI.total_amount"
      }
     ]
    },
    {
     "title": "Etiqueta",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Etiquetas.service_tag AS \"Etiqueta\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN contract_service_tags Etiquetas ON Etiquetas.id = RCI.contract_service_tag_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n"
      }
     ]
    },
    {
     "title": "Titulo Etiqueta",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Etiquetas.title AS \"Etiqueta Titulo\"\r\nFROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN contract_service_tags Etiquetas ON Etiquetas.id = RCI.contract_service_tag_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n"
      }
     ]
    },
    {
     "title": "Endereço",
     "type": "stat",
     "description": "Endereço vinculado diretamente ao Produto",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\nCONCAT (\r\n    Endereco.street,\r\n    ', ',\r\n    Endereco.number,\r\n    CASE\r\n      WHEN Endereco.address_complement IS NOT NULL\r\n      AND Endereco.address_complement != '' THEN CONCAT (' - ', Endereco.address_complement)\r\n      ELSE ''\r\n    END,\r\n    ' - ',\r\n    Endereco.neighborhood\r\n  )\r\n AS \"Endereço Completo\"\r\n  FROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN authentication_contracts AC ON AC.contract_item_id = RCI.id\r\n  JOIN people_addresses Endereco ON Endereco.id = AC.people_address_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n"
      }
     ]
    },
    {
     "title": "CEP",
     "type": "stat",
     "description": "CEP vinculado diretamente ao Produto",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Endereco.postal_code as \"CEP\"\r\n\r\n  FROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN authentication_contracts AC ON AC.contract_item_id = RCI.id\r\n  JOIN people_addresses Endereco ON Endereco.id = AC.people_address_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n"
      }
     ]
    },
    {
     "title": "Cidade",
     "type": "stat",
     "description": "Cidade vinculado diretamente ao Produto",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  CONCAT(Endereco.city, ' - ', Endereco.state, ', ', Endereco.country) as \"Endereço\"\r\n\r\n  FROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN authentication_contracts AC ON AC.contract_item_id = RCI.id\r\n  JOIN people_addresses Endereco ON Endereco.id = AC.people_address_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n\r\n"
      }
     ]
    },
    {
     "title": "Endereço",
     "type": "stat",
     "description": "Endereço vinculado diretamente ao Contrato especifico",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\nCONCAT (\r\n    Endereco.street,\r\n    ', ',\r\n    Endereco.number,\r\n    CASE\r\n      WHEN Endereco.address_complement IS NOT NULL\r\n      AND Endereco.address_complement != '' THEN CONCAT (' - ', Endereco.address_complement)\r\n      ELSE ''\r\n    END,\r\n    ' - ',\r\n    Endereco.neighborhood\r\n  )\r\n AS \"Endereço Completo\"\r\n  FROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN authentication_contracts AC ON AC.contract_id = Contratos.id AND AC.service_product_id = Produtos.id\r\n  JOIN people_addresses Endereco ON Endereco.id = AC.people_address_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n    LIMIT 1\r\n\r\n"
      }
     ]
    },
    {
     "title": "CEP",
     "type": "stat",
     "description": "CEP vinculado diretamente ao Contrato especifico",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  Endereco.postal_code as \"CEP\"\r\n\r\n  FROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN authentication_contracts AC ON AC.contract_id = Contratos.id AND AC.service_product_id = Produtos.id\r\n  JOIN people_addresses Endereco ON Endereco.id = AC.people_address_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n    LIMIT 1\r\n\r\n    \r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Cidade",
     "type": "stat",
     "description": "CEP vinculado diretamente ao Contrato especifico",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  CONCAT(Endereco.city, ' - ', Endereco.state, ', ', Endereco.country) as \"Endereço\"\r\n\r\n  FROM\r\n  people Clientes\r\n  JOIN contracts Contratos ON Clientes.id = Contratos.client_id\r\n  AND Contratos.deleted = false\r\n  INNER JOIN people_crm_informations pci ON pci.person_id = Clientes.id\r\n  INNER JOIN people AS Vendedor ON Vendedor.id = pci.proprietary_id\r\n  LEFT JOIN contract_items RCI ON RCI.contract_id = Contratos.id\r\n  AND RCI.deleted = false\r\n  LEFT JOIN service_products Produtos ON Produtos.id = RCI.service_product_id\r\n  JOIN authentication_contracts AC ON AC.contract_id = Contratos.id AND AC.service_product_id = Produtos.id\r\n  JOIN people_addresses Endereco ON Endereco.id = AC.people_address_id\r\nWHERE\r\n  -- RCI.is_composition = false\r\n   Produtos.code IN ($Produtos)\r\n  AND Contratos.id IN ($Contrato)\r\n  AND Vendedor.id = $GN\r\n    and RCI.deleted = false\r\n    LIMIT 1\r\n\r\n    \r\n\r\n"
      }
     ]
    }
   ]
  }
 ]
}